import Sidebar from "./components/Sidebar";
import { StateProvider } from "./context/context";
import TopBar from "./components/TopBar";
import { CookiesProvider } from "next-client-cookies/server";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Dashboard | KForCody",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CookiesProvider>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            className={"text-sm"}
            theme="dark"
          />
          <TopBar />
          <StateProvider>
            <Sidebar>{children}</Sidebar>
          </StateProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
